#!/bin/sh
# chkconfig: 35 99 1
# description: UMMS daemon

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    try_command /usr/libexec/umms-server > /dev/null &
}

stop_function() {
    try_command killall umms-server
}

status_function() {
    if ps -ax | grep umms-server >/dev/null 2>&1 ; then
        echo $"umms-server daemon is running"
        RETVAL=0
    else
        echo $"no umms-server daemon"
        RETVAL=3
    fi
}

case $1 in
    "start")
    echo "start to run umms-server daemon"
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    "status")
    status_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
esac
